#pragma once
#include "sysdep.h"
#include "typestubs.h"
#include "structs.h"

extern void ch_restore(struct char_data *ch, bool announce);
extern void ch_ghostify(struct char_data *ch);
extern void ch_restore_by(struct char_data *ch, struct char_data *by);
extern void ch_resurrect(struct char_data *ch, enum ResurrectionMode mode);
extern void ch_teleport_to(struct char_data *ch, IDXTYPE rnum);
extern bool ch_in_room_range(struct char_data *ch, IDXTYPE low_rnum, IDXTYPE high_rnum);
extern void ch_restoreLF(struct char_data *ch, bool announce);
extern bool ch_isFullVitals(struct char_data *ch);
extern void ch_restoreVitals(struct char_data *ch, bool announce);
extern void ch_restoreStatus(struct char_data *ch, bool announce);
extern void ch_restoreLimbs(struct char_data *ch, bool announce);
extern double ch_speednar(struct char_data *ch);
extern bool ch_isWeightedPL(struct char_data *ch);
extern void ch_apply_kaioken(struct char_data *ch, int times, bool announce);
extern void ch_remove_kaioken(struct char_data *ch, int8_t announce);
extern int64_t ch_getEffMaxPL(struct char_data *ch);
extern int64_t ch_getAvailableCarryWeight(struct char_data *ch);
extern int64_t ch_getCurCarriedWeight(struct char_data *ch);
extern int64_t ch_getCurGearWeight(struct char_data *ch);
extern int64_t ch_getMaxCarryWeight(struct char_data *ch);
extern void ch_setStatusKnockedOut(struct char_data *ch);
extern void ch_cureStatusPoison(struct char_data *ch, bool announce);
extern void ch_cureStatusBurn(struct char_data *ch, bool announce);
extern void ch_cureStatusKnockedOut(struct char_data *ch, bool announce);
extern int64_t ch_gainBasePLPercent(struct char_data *ch, double amt, bool trans_mult);
extern int64_t ch_loseBasePLPercent(struct char_data *ch, double amt, bool trans_mult);
extern int64_t ch_gainBaseKIPercent(struct char_data *ch, double amt, bool trans_mult);
extern int64_t ch_gainBaseSTPercent(struct char_data *ch, double amt, bool trans_mult);
extern void ch_gainBaseAllPercent(struct char_data *ch, double amt, bool trans_mult);
extern int64_t ch_loseBasePL(struct char_data *ch, int64_t amt, bool trans_mult);
extern int64_t ch_gainBaseKI(struct char_data *ch, int64_t amt, bool trans_mult);
extern int64_t ch_gainBaseST(struct char_data *ch, int64_t amt, bool trans_mult);
extern int64_t ch_gainBasePL(struct char_data *ch, int64_t amt, bool trans_mult);
extern int64_t ch_decCurLFPercent(struct char_data *ch, double amt, int64_t floor);
extern int64_t ch_incCurLFPercent(struct char_data *ch, double amt, bool limit_max);
extern int64_t ch_decCurLF(struct char_data *ch, int64_t amt, int64_t floor);
extern int64_t ch_incCurLF(struct char_data *ch, int64_t amt, bool limit_max);
extern int64_t ch_setCurLFPercent(struct char_data *ch, double amt);
extern int64_t ch_setCurLF(struct char_data *ch, int64_t amt);
extern bool ch_isFullLF(struct char_data *ch);
extern int64_t ch_getPercentOfMaxLF(struct char_data *ch, double amt);
extern int64_t ch_getPercentOfCurLF(struct char_data *ch, double amt);
extern double ch_getCurLFPercent(struct char_data *ch);
extern int64_t ch_getMaxLF(struct char_data *ch);
extern int64_t ch_getCurLF(struct char_data *ch);
extern void ch_restoreST(struct char_data *ch, bool announce);
extern int64_t ch_decCurSTPercent(struct char_data *ch, double amt, int64_t floor);
extern int64_t ch_incCurSTPercent(struct char_data *ch, double amt, bool limit_max);
extern int64_t ch_decCurST(struct char_data *ch, int64_t amt, int64_t floor);
extern int64_t ch_incCurST(struct char_data *ch, int64_t amt, bool limit_max);
extern int64_t ch_setCurSTPercent(struct char_data *ch, double amt);
extern int64_t ch_setCurST(struct char_data *ch, int64_t amt);
extern bool ch_isFullST(struct char_data *ch);
extern int64_t ch_getPercentOfMaxST(struct char_data *ch, double amt);
extern double ch_getCurSTPercent(struct char_data *ch);
extern int64_t ch_getBaseST(struct char_data *ch);
extern int64_t ch_getEffBaseST(struct char_data *ch);
extern int64_t ch_getMaxST(struct char_data *ch);
extern int64_t ch_getCurST(struct char_data *ch);
extern void ch_restoreKI(struct char_data *ch, bool announce);
extern int64_t ch_decCurKIPercent(struct char_data *ch, double amt, int64_t floor);
extern int64_t ch_incCurKIPercent(struct char_data *ch, double amt, bool limit_max);
extern int64_t ch_decCurKI(struct char_data *ch, int64_t amt, int64_t floor);
extern int64_t ch_incCurKI(struct char_data *ch, int64_t amt, bool limit_max);
extern int64_t ch_setCurKIPercent(struct char_data *ch, double amt);
extern int64_t ch_setCurKI(struct char_data *ch, int64_t amt);
extern bool ch_isFullKI(struct char_data *ch);
extern int64_t ch_getPercentOfMaxKI(struct char_data *ch, double amt);
extern int64_t ch_getPercentOfCurKI(struct char_data *ch, double amt);
extern int64_t ch_getBaseKI(struct char_data *ch);
extern int64_t ch_getEffBaseKI(struct char_data *ch);
extern int64_t ch_getMaxKI(struct char_data *ch);
extern int64_t ch_getCurKI(struct char_data *ch);
extern bool ch_isFullPL(struct char_data *ch);
extern int64_t ch_getPercentOfMaxPL(struct char_data *ch, double amt);
extern int64_t ch_getPercentOfCurPL(struct char_data *ch, double amt);
extern double ch_getCurPLPercent(struct char_data *ch);
extern int64_t ch_getBasePL(struct char_data *ch);
extern int64_t ch_getEffBasePL(struct char_data *ch);
extern int64_t ch_getCurPL(struct char_data *ch);
extern int64_t ch_getMaxPL(struct char_data *ch);
extern int64_t ch_getMaxPLTrans(struct char_data *ch);
extern void ch_restoreHealth(struct char_data *ch, bool announce);
extern int64_t ch_decCurHealthPercent(struct char_data *ch, double amt, int64_t floor);
extern int64_t ch_incCurHealthPercent(struct char_data *ch, double amt, bool limit_max);
extern int64_t ch_decCurHealth(struct char_data *ch, int64_t amt, int64_t floor);
extern int64_t ch_incCurHealth(struct char_data *ch, int64_t amt, bool limit_max);
extern int64_t ch_setCurHealthPercent(struct char_data *ch, double amt);
extern int64_t ch_setCurHealth(struct char_data *ch, int64_t amt);
extern bool ch_isFullHealth(struct char_data *ch);
extern int64_t ch_getPercentOfMaxHealth(struct char_data *ch, double amt);
extern int64_t ch_getPercentOfCurHealth(struct char_data *ch, double amt);
extern double ch_getCurHealthPercent(struct char_data *ch);
extern int64_t ch_getMaxHealth(struct char_data *ch);
extern int64_t ch_getCurHealth(struct char_data *ch);
extern int ch_calcGravCost(struct char_data *ch, int64_t num);
extern int ch_wearing_android_canister(struct char_data *ch);
extern bool ch_is_soft_cap(struct char_data *ch, int64_t type, long double mult);
extern int64_t ch_calc_soft_cap(struct char_data *ch);
extern int ch_calcTier(struct char_data *ch);
extern bool ch_can_tolerate_gravity(struct char_data *ch, int grav);
extern bool ch_hasTail(struct char_data *ch);
extern void ch_loseTail(struct char_data *ch);
extern void ch_gainTail(struct char_data *ch);
extern int ch_getCurrentTransTier(struct char_data *ch);
extern int ch_transFlagToTier(int flag);
extern bool ch_checkCanTransform(struct char_data *ch);
extern bool ch_getSoftType(struct char_data *ch);
extern const char* ch_juggleRaceName(struct char_data *ch, bool capitalized);
extern void ch_echoRevert(struct char_data *ch, int tier);
extern void ch_echoTransform(struct char_data *ch, int tier);
extern void ch_displayTransReq(struct char_data *ch);
extern bool ch_checkTransUnlock(struct char_data *ch, int tier);
extern void ch_displayForms(struct char_data *ch);
extern const struct transform_bonus* ch_getTransMap(struct char_data *ch);
extern int64_t* ch_getSoftMap(struct char_data *ch);
extern struct transform_bonus ch_getCurForm(struct char_data *ch);
extern struct transform_bonus ch_findForm(struct char_data *ch, char *arg);